name: Build and Deploy

on: [push, repository_dispatch]

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: Build
        run: GATSBY_CPU_COUNT=2 yarn build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /opt/www/0xcb.dev
          remote_host: node.0xcb.dev
          remote_user: root
          remote_port: 11988
          remote_key: ${{ secrets.DEPLOY }}
